CREATE TABLE `reservas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id_horario_sessao` int NOT NULL,
  `data_sessao` date NOT NULL DEFAULT '2024-01-01' COMMENT 'Data específica da sessão reservada',
  `id_filme` int NOT NULL,
  `id_cinema` int NOT NULL,
  `id_tipo_sessao` int NOT NULL,
  `id_usuario` int DEFAULT NULL,
  `nome_cliente` varchar(255) NOT NULL,
  `email_cliente` varchar(255) NOT NULL,
  `telefone_cliente` varchar(50) DEFAULT NULL,
  `data_reserva` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('pendente','confirmada','cancelada') DEFAULT 'confirmada',
  `total` decimal(10,2) NOT NULL DEFAULT '0.00',
  `metodo_pagamento` varchar(50) NOT NULL DEFAULT 'cartao',
  `lugares` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `filme_id` (`id_filme`),
  KEY `cinema_id` (`id_cinema`),
  KEY `tipo_sessao_id` (`id_tipo_sessao`),
  KEY `idx_data_sessao` (`data_sessao`),
  KEY `fk_reserva_horario_sessao` (`id_horario_sessao`),
  CONSTRAINT `fk_reserva_horario_sessao` FOREIGN KEY (`id_horario_sessao`) REFERENCES `horarios_sessao` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=878 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;